source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# See https://github.com/facebook/react-native/issues/42697
gem 'cocoapods', '1.14.3'
